### ISSUE TITLE
Bibliogram link down (https://bibliogram.pussthecat.org/)

### ISSUE THREAD

**Issue by Mennaruuk** [PussTheCat-org/PussTheCat.org#1]
I'm getting a 502 Bad Gateway error message when opening PussTheCat.org's Bibliogram instance.

**Comment by Mennaruuk** [comment]
Seems like a couple others are down:

- [bibliogram.art](https://bibliogram.art)
- [bibliogram.13ad.de](https://bibliogram.13ad.de)

**Comment by TheFrenchGhosty** [comment]
@Mennaruuk I know, this is an issue since I updated node/npm.

If I start Bibliogram it will spam the log, and crash after 2 minutes.

We discussed it in the Bibliogram Matrix room, and there's not really any solution.

Sadly the docker container that currently exist is unusable, so I can't really do anything.

**Comment by Mennaruuk** [comment]
Thank you for your elucidation. I was reading about [Bibliogram's future](https://proxy.vulpes.one/gemini/cadence.moe/gemlog/2020-12-17-future-of-bibliogram.bliz) and how it's been hurt by Instagram's blanket of IP address blocking, so my mind immediately jumped to that when I saw the error message. This seems to be a different issue.
